---
- hosts: 10.10.5.184
  become: no
  environment:
    MINIO_ACCESS_KEY: "JXTFBt1pDco6bUtSukj6"
    MINIO_SECRET_KEY: "QffFMVJyZqiVOhvJFEZZAKWHGCsrvxd6VcKrLVA6"
  tasks:
   - name: Download file from Minio
     win_get_url:
      url: "https://10.10.5.81:9091/security/SQLite/Screenshot from 2023-10-11 09-03-48.png"
      dest: c:\\Users\\
      validate_certs: no
