---
- name: Download and Copy Minio to Windows
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Create Minio Directory
      win_file:
        path: C:\Minio
        state: directory
      become: yes
      become_user: Administrator  # Replace with the appropriate username

    - name: Download Minio
      win_get_url:
        url: http://10.10.5.81/#/jobs/playbook/187/output/windows-amd64/minio.exe
        dest: arc/Arc_11102023
      become: yes
      become_user: Administrator  # Replace with the appropriate username
