---
- name: Download and Copy Minio to Windows
  hosts: 10.10.5.181
  gather_facts: no
  become: yes
  tasks:
    - name: Create Minio Directory
      win_file:
        path: C:\Minio
        state: directory

    - name: Download Minio
      win_get_url:
        url: https://10.10.5.81:9091/server/minio/release/windows-amd64/minio.exe
        dest: C:/mc
