---
- name: Uninstall SQLite on Windows
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Stop SQLite if running
      win_service:
        name: SQLiteServiceName  # Replace with the actual SQLite service name
        state: stopped
      ignore_errors: yes

    - name: Remove SQLite directory
      win_file:
        path: C:\SQLite  # Replace with the path where SQLite is installed
        state: absent

    - name: Remove Temp Directory
      win_file:
        path: C:\Temp
        state: absent
