---
- name: Download files from MinIO
  hosts: 10.10.5.184
  gather_facts: no
  tasks:
    - name: Ensure local directory exists
      file:
        path: C:\mc
        state: directory

    - name: Download files from MinIO
      command: mc cp minio/security/mnt/data/security/SQLite C:\mc/
      environment:
        MC_HOST: "https://10.10.5.76:9001"
        MC_ACCESS_KEY: "DW1v3EfdBLR0J1GVhdjC"
        MC_SECRET_KEY: "5VytN79seVFxeYmAmwLlYUF4O0rp0Hlnex50GyTf"
