---
- name: Uninstall SQLite from Windows
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Remove SQLite Directory
      win_file:
        path: C:\SQLite
        state: absent

    - name: Remove SQLite Zip File
      win_file:
        path: C:\Temp\sqlite-tools-win32-x86-3430100.zip
        state: absent

    - name: Remove Temp Directory
      win_file:
        path: C:\Temp
        state: absent

    - name: Remove SQLite from PATH
      win_path:
        elements:
          - C:\SQLite
        state: absent
