---
- name: Install SQLite on Windows
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory
    - name: Download SQLite precompiled binaries
      win_get_url:
        url: https://www.sqlite.org/2023/sqlite-tools-win32-x86-3430100.zip
        dest: C:\Temp\sqlite-tools-win32-x86-3430100.zip
    - name: Extract SQLite binaries
      win_unzip:
        src: C:\Temp\sqlite-tools-win32-x86-3430100.zip
        dest: C:\SQLite
    - name: Add SQLite to PATH
      win_path:
        elements:
          - C:\SQLite
        state: present
