---
- hosts: 10.10.5.184
  become: yes
  environment:
    MINIO_ACCESS_KEY: "DW1v3EfdBLR0J1GVhdjC"
    MINIO_SECRET_KEY: "5VytN79seVFxeYmAmwLlYUF4O0rp0Hlnex50GyTf"
  tasks:
    - name: Download file from Minio
      win_get_url:
        url: "https://10.10.5.81:9001/minio/data/shinobi/Arc_11102023"
        dest: C:\Arc
        validate_certs: no
