---
- name: Download files from MinIO
  hosts: 10.10.5.184
  gather_facts: yes  # You can set this to yes or no based on your requirements
  tasks:
    - name: Ensure local directory exists
      file:
        path: C:\myfiles
        state: directory

    - name: Download files from MinIO
      command: mc cp minio/security/mnt/data/security/SQLite C:\myfiles/
      environment:
        MC_HOST: "https://10.10.5.76:9001"  # Replace with your MinIO server URL
        MC_ACCESS_KEY: "DW1v3EfdBLR0J1GVhdjC"
        MC_SECRET_KEY: "5VytN79seVFxeYmAmwLlYUF4O0rp0Hlnex50GyTf"
