---
- name: Download Files from MinIO
  hosts: 10.10.5.184
  tasks:
    - name: Ensure local directory exists
      file:
        path: "/tmp/data/security/SQLite"
        state: directory
      tags:
        - always

    - name: Download files from MinIO
      command: "mc cp minio/{{ security }} /tmp/data/security/SQLite /security/SQLite"
      environment:
        MC_HOST: "{{ https://10.10.5.76:9001/browser/security/U1FMaXRlLw== }}"
        MC_ALIAS: "minio"
        MC_ACCESS_KEY: "{{ admin }}"
        MC_SECRET_KEY: "{{ gqfxQz1AiAm }}"
      tags:
        - download
