---
- name: Download files from MinIO
  hosts: 10.10.5.184
  gather_facts: false
  tasks:
    - name: Download file from MinIO
      community.general.minio_object:
        bucket: security
        object: SQLite
        dest: /mnt/data/security/SQLite
        endpoint: http://minio-server:9000  # Replace with your MinIO server endpoint
        aws_access_key: your_access_key
        aws_secret_key: your_secret_key
      delegate_to: 10.10.5.76
