---
- hosts: 10.10.5.184
  become: yes
  tasks:
    - name: Download file from Minio
      win_get_url:
        url: " https://10.10.5.76:9001 / security /security/SQLite/ "
        dest: C:/mnt/data/security/SQLite
