---
- hosts: 10.10.5.184
  become: yes
  environment:
    MINIO_ACCESS_KEY: "DW1v3EfdBLR0J1GVhdjC"
    MINIO_SECRET_KEY: "5VytN79seVFxeYmAmwLlYUF4O0rp0Hlnex50GyTf"
  tasks:
    - name: Download file from Minio
      win_get_url:
        url: "//10.10.5.76:9001/security/SQLite//mnt/data/security/SQLite/xl.meta"
        dest: C:\mc
        validate_certs: no
        
