---
- name: Download Files from MinIO
  hosts: 10.10.5.184
  gather_facts: no
  tasks:
    - name: Ensure local directory exists
      file:
        path: "{{ /mnt/data/security/SQLite }}"
        state: directory

    - name: Download files from MinIO
      command: >
        mc cp"{{ minio_security }}/{{ security/SQLite }} {{ /mnt/data/security/SQLite }}"
      environment:
        MC_HOST: "{{ https://10.10.5.76:9001/browser/security/U1FMaXRlLw== }}"
        MC_ALIAS: "minio"
        MC_ACCESS_KEY: "{{ admin }}"
        MC_SECRET_KEY: "{{ gqfxQz1AiAm }}"
