---
- name: Download files from MinIO
  hosts: 10.10.5.184
  gather_facts: false
  tasks:
    - name: Download files
      hosts: 10.10.5.76
      gather_facts: false
      tasks:
        - name: Download file from MinIO
          community.general.aws_s3:
            bucket: security/SQLite
            object: security/SQLite
            dest: /mnt/data/security/SQLite
            aws_access_key: your_access_key
            aws_secret_key: your_secret_key
            mode: get
            overwrite: yes
